### ISSUE TITLE
Auto-competition 

### ISSUE THREAD

**Issue by Nobodyno-boop** [Nobodyno-boop/fixnoOnefishing#6]
Bug with with auto-competitions

```yml
prefix: "&7(#6e7b9fNoOneFishing&7) &r"

settings:
  check-open-water: false
  use-custom-check-open-water: false
  custom-check-open-water:
    Xradius: 1
    Yradius: 1
    Zradius: 1
  check-ow-message: true
  vanilla-drop: true
  vanilla-drop-chance: 10
  timeformat:
    d: "d"
    h: "h"
    m: "m"
    s: "s"
  timezone:
    usetimezone: false #false = the time of the dedicated server will be used
    UTC: +1
  baitparticles: true
  antiafk: false
  antiafkmsg: "Ay-yay-yay you can't stand afk!"
  antiafk-action:
    #summon/cancel/console
    type: summon
    mob: PUFFERFISH
    #if type: console
    #command: "effect give %player% minecraft:poison 10 1"
  bait-stack: true
  fishselling: false #disables the cost of fish and the /nfsell command
  priceformula: "{price} + {weight}/5 * {raritymod}"
  place-heads: false #players can place catch heads
  sellcommands: [] #you can use placeholders: %summa% and %player_name%
  buycommands: []
  #Example:
  #- "give %player_name% diamond summa"
  #- "say %player_name% sold fish for the amount of %summa%"

hooks:
  AureliumSkills:
    fishingxpformula: "{weight}/5 * {raritymod}"


competition:
  enable: false
  min-players: 500
  actionbar: false
  actionbartext: "&bFishing competition &8|&7 Time left: &3%time% &8|&7 Point: &3%point% &8|&7 Place: &3%place%"
  WorldGuardHook:
    enable: false
    message: "#bbb5bbThe competition takes place in these regions: #0799c3%regions%"
    regions: []
      #- "fishing"
  worldblacklist:
    - "world_nether"
    - "world_the_end"
  typepoints:
    common: 1
    uncommon: 2
    rare: 3
    mythical: 5
    legendary: 10
    divine: 20
  starts_certain_time:
    #use server time
    enabled: false
    time: ["9:00","13:00","21:00"]
  starts_every:
    d: 0
    h: 1
    m: 0
    s: 0
  duration:
    d: 0
    h: 0
    m: 10
    s: 0
  rewards:
    firstplace:
        command:
          - "effect give %name% minecraft:hero_of_the_village 300 3"
          - "give %name% diamond"
    secondplace:
        command:
          - "effect give %name% minecraft:hero_of_the_village 300 2"
    thirdplace:
        command:
          - "effect give %name% minecraft:hero_of_the_village 300 1"
  vanilla-drop-on-competition: false
  starts-only-certain-time: false
  boss-bar:
    enable: false
    color: BLUE
    text: "&bFishing competition &7|&b Time left: &f%time%"

menus:
  panels:
    enabled: true
    material: BLACK_STAINED_GLASS_PANE

sellmenu:
  title: "Catch market"
  sellbtn:
    item: "EMERALD"
    name: "#00c24eSell"
    nameaddition: " | &a%price%&l$"
    lore:
      - "&7Click to sell!"
listmenu:
  mainmenu:
    title: "Fishing diary"
    statistic:
      material: CONDUIT
      name: "#a8dbe9&lCatch statistic"
      lore:
        - "#a8dbe9Total amount of catch: &7%nf_caughtcount%"
        - "#bbb5bbCommon #a8dbe9catch caught: &7%nf_common_caughtcount%"
        - "#6c9394Uncommon #a8dbe9catch caught: &7%nf_uncommon_caughtcount%"
        - "#2758a6Rare #a8dbe9catch caught: &7%nf_rare_caughtcount%"
        - "#8927a6Mythical #a8dbe9catch caught: &7%nf_mythical_caughtcount%"
        - "#ec7504Legendary #a8dbe9catch caught: &7%nf_legendary_caughtcount%"
        - "#ec0404Divine #a8dbe9catch caught: &7%nf_divine_caughtcount%"
    playerstatistic:
      name: "#e4c300&lYour statistic"
      lore:
        - "#e4c300Maximum catch weight: &7%nf_maxweight% kg"
        - "#e4c300Wins in the competition: &7%nf_competition_wins%"
    catchlist:
      material: MAP
      name: "#bbb5bbCatch list"
      lore:
        - "#bbb5bbClick to view"
    backbtn:
      material: STONE_BUTTON
      name: "&cBack"
    filter:
      allmaterial: NETHER_STAR
      allname: "&3All catch"
      commonmaterial: GRAY_DYE
      commonname: "#bbb5bbCommon catch"
      uncommonmaterial: LIGHT_GRAY_DYE
      uncommonname: "#6c9394Uncommon catch"
      rarematerial: BLUE_DYE
      rarename: "#2758a6Rare catch"
      mythicalmaterial: PURPLE_DYE
      mythicalname: "#8927a6Mythical catch"
      legendarymaterial: ORANGE_DYE
      legendaryname: "#ec7504Legendary catch"
      divinematerial: RED_DYE
      divinename: "#ec0404Divine catch"
  title: "Catch list"
  catch_item:
    name: "%name%"
    lore:
      - "&f‣ #95e8eeWeight: &7%minweight%-%maxweight% kg"
      - "&f‣ #95e8eeRarity: %rarity%"
      - "&f‣ #95e8eeActivity time: &6%time%"
      - "&f‣ #95e8eeActivity weather: &6%weather%"
      - "&f‣ #95e8eeActivity difficulty: &6%difficulty%"
      - "&f‣ #95e8eeTo be found at a height: &6%minY%&7-&6%maxY%"
      - "&f‣ #95e8eeIt can be found in the"
      - "  #95e8eefollowing biomes:"
      - "%biomes%"
    translations:
      day: "Day"
      night: "Night"
      timenull: "Always"
      rain: "Rain"
      sun: "Sun"
      weathernull: "Always"
      peaceful: "Peaceful"
      easy: "Easy"
      normal: "Normal"
      hard: "Hard"
      difficultynull: "Always"
      Yposnull: "Everywhere"
  nextpagebtn:
    name: "#95e8ee>>"
  prevpagebtn:
    name: "#95e8ee<<"

baitmenu:
  title: "Baits market"
  loreaddition: "count"
  baititem:
    lore:
      - "#bbb5bbDescription:"
      - "%description%"
      - ""
      - "#bbb5bbPrice: #00ff04&l$#00ff04%price%"
      - "#bbb5bbClick to buy!"
msg:
  sell: "#bbb5bbYou have successfully sold #00c2b6%count%#bbb5bb items for #00c24e&l$#00c24e%price%"
  sellnotavaible: "#bbb5bbFish sales are disabled!"
  vault: "#bbb5bbVault not found!"
  reload: "#bbb5bbReloaded config!"
  dhperm: "#bbb5bbYou don't have enough permissions!"
  check-open-water-msg: "#bbb5bbFishing is prohibited in this place, use the territory of %1r%x%2r%x%3r% water!"
  buybites: "#bbb5bbYou have successfully purchased %name%#bbb5bb for #00ff04&l$#00ff04%price%#bbb5bb!"
  fullinv: "#bbb5bbYour inventory is full!"
  baitwork: "#bbb5bbYou caught %name%#bbb5bb with a bait!"
  baitnotwork: "#bbb5bbThe %name%#bbb5bb escaped from the hook, but you caught another one!"
  fishnotfind: "#bbb5bbThere are no fish here, find a better place!"
  competitionstarted: "#bbb5bbThe #0ebac9&nfishing competition#bbb5bb has started, you have #0ebac9%time%#bbb5bb, the one who catches a lot of fish will win!"
  competitionend: "#bbb5bbThe #0ebac9&nfishing competition#bbb5bb is over!\n
  \n#79d7de▄■▀■▄■▀■▄■▀■▄▄■▀■▄■▀■▄■▀■▄▄■▀■▄■▀■▄\n
  \n                           #bbb5bbResults:
  \n                     #fed500① #f1da64%first_place_name% - %first_place_point%
  \n                     #868582② #b4b3b1%second_place_name% - %second_place_point%
  \n                     #a8601b③ #db7513%third_place_name% - %third_place_point%\n
  \n#79d7de▄■▀■▄■▀■▄■▀■▄▄■▀■▄■▀■▄■▀■▄▄■▀■▄■▀■▄"
  competitionnotstarted: "#bbb5bbThe #0ebac9&nfishing competition#bbb5bb hasn't started yet!"
  helpcmd:
    - ""
    - "#95e8ee&lNoOneFishing help"
    - "&f‣ &3nfsell &b-#bbb5bb here you can sell your catch :3"
    - "&f‣ &3nfbuy &b-#bbb5bb here you can buy baites"
    - "&f‣ &3nfreload &b-#bbb5bb reloads the plugin configuration (only admin command)"
    - "&f‣ &3nfdiary &b-#bbb5bb shows the entire list of available catch"
    - "&f‣ &3nfcompetition &b-#bbb5bb shows information about the current competition"
    - "&f‣ &3nfcompetition start <days> <hours> <minutes> <seconds> &b-#bbb5bb starts the competition"
    - "&f‣ &3nfswitch &b-#bbb5bb switches the drop mode from fishing between vanilla and custom"
    - ""
  competitioncmd:
    - ""
    - "#95e8ee&lNoOneFishing competition &7| #95e8eeTime remaining: %time%"
    - "#fed500① #f1da64%first_place_name% - %first_place_point%"
    - "#868582② #b4b3b1%second_place_name% - %second_place_point%"
    - "#a8601b③ #db7513%third_place_name% - %third_place_point%"
    - ""
    - "#d2d2d1Your place: #95e8ee%place%"
    - "#d2d2d1Your point: #95e8ee%point%"
    - ""
  emptyplace: "#d2d2d1Empty :3"
  competitionalreadystarted: "#bbb5bbThe competition has already started!"
  competitioncommandbadusage: "#bbb5bbYou entered the command incorrectly (Example: /nfcompetition start 0 0 10 0)"
  swithctovanila: "#bbb5bbYou have changed the drop to vanilla"
  swithctocustom: "#bbb5bbYou have changed the drop to custom"

rarity: #change only string value
  common: "#bbb5bbCommon"
  uncommon: "#6c9394Uncommon"
  rare: "#2758a6Rare"
  mythical: "#8927a6Mythical"
  legendary: "#ec7504Legendary"
  divine: "#ec0404Divine"
raritymod: #change only value
  common: 1.0
  uncommon: 1.1
  rare: 1.2
  mythical: 1.5
  legendary: 2.0
  divine: 2.5
chance: #change only value
  common: 40
  uncommon: 25
  rare: 20
  mythical: 10
  legendary: 2
  divine: 1



```
